"use client";
import {useEffect,useRef} from "react";
const VS="attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}";
const FS="precision highp float;\nuniform vec2 R;uniform float T,AUD,PWR,MOOD;uniform vec3 COL;uniform vec2 M;\nfloat h(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,45.164)))*43758.5453);}\nfloat n3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);\nfloat a=mix(mix(mix(h(i),h(i+vec3(1,0,0)),f.x),mix(h(i+vec3(0,1,0)),h(i+vec3(1,1,0)),f.x),f.y),\nmix(mix(h(i+vec3(0,0,1)),h(i+vec3(1,0,1)),f.x),mix(h(i+vec3(0,1,1)),h(i+vec3(1,1,1)),f.x),f.y),f.z);return a;}\nfloat fbm(vec3 p){float s=0.,a=.5;for(int i=0;i<4;i++){s+=a*n3(p);p*=2.03;a*=.5;}return s;}\nfloat map(vec3 p){float t=T*.35;vec3 q=p;\nfloat lob=sin(atan(q.x,q.z)*6.0+t*.4)*0.045*(1.0+AUD*1.6);\nfloat bump=fbm(q*2.6+vec3(0.,t*.5,0.))*0.30;\nfloat br=sin(T*1.1)*0.025+AUD*0.18;float rg=sin(q.y*9.0+t)*0.018;\nreturn length(q)-(0.95+br+lob+rg+(bump-0.15)*(0.55+PWR*0.5));}\nvec3 nrm(vec3 p){vec2 e=vec2(.0028,0.);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}\nvoid main(){vec2 uv=(gl_FragCoord.xy-0.5*R)/min(R.x,R.y);\nvec3 ro=vec3(0.,0.,3.05);vec3 rd=normalize(vec3(uv,-1.55));\nfloat ax=M.y*0.5,ay=M.x*0.9+T*0.07;\nmat2 rx=mat2(cos(ax),-sin(ax),sin(ax),cos(ax));mat2 ry=mat2(cos(ay),-sin(ay),sin(ay),cos(ay));\nro.yz*=rx;rd.yz*=rx;ro.xz*=ry;rd.xz*=ry;\nfloat d=0.,t=0.;vec3 p;bool hit=false;\nfor(int i=0;i<64;i++){p=ro+rd*t;d=map(p);if(d<0.002){hit=true;break;}t+=d*0.85;if(t>6.)break;}\nvec3 col=vec3(0.);\nif(hit){vec3 n=nrm(p);vec3 l1=normalize(vec3(.55,.75,.6)),l2=normalize(vec3(-.7,-.2,.4));\nfloat df=max(dot(n,l1),0.),df2=max(dot(n,l2),0.)*.35;\nfloat sp=pow(max(dot(reflect(-l1,n),-rd),0.),42.);\nfloat fr=pow(1.-max(dot(n,-rd),0.),2.6);float ss=pow(max(dot(n,-l1),0.),1.6)*.35;\nvec3 base=COL*(0.55+MOOD*0.6);col=base*(0.18+df*0.95+df2)+vec3(1.)*sp*0.85+base*ss;\ncol+=vec3(1.,.55,.28)*fr*(0.30+PWR*0.55);\nfloat g2=smoothstep(.02,.0,abs(fract(atan(p.x,p.z)/6.2831*12.)-.5)-.46);col*=1.-g2*0.22;\nfloat vn=smoothstep(.55,.85,fbm(p*5.0+vec3(0.,T*.3,0.)));col+=COL*vn*0.22*(0.4+AUD*2.0);\n}else{float g=exp(-length(uv)*3.4);col+=COL*g*0.09*(0.4+AUD);}\ncol=pow(col,vec3(0.86));gl_FragColor=vec4(col,hit?1.0:min(0.5,col.r+col.g+col.b));}";
export default function VoiceGarden({state,signal}:{state:string;signal:{current:{level:number}}}){
 const net=useRef<HTMLCanvasElement>(null),core=useRef<HTMLCanvasElement>(null),live=useRef({state,since:0});
 useEffect(()=>{if(live.current.state!==state)live.current={state,since:performance.now()};},[state]);
 useEffect(()=>{
 const n=net.current,c=core.current;if(!n||!c)return;const ctx=n.getContext("2d");if(!ctx)return;
 const gl=c.getContext("webgl",{alpha:true});let program:WebGLProgram|null=null,buffer:WebGLBuffer|null=null;const shaders:WebGLShader[]=[],u:Record<string,WebGLUniformLocation|null>={};
 if(gl)try{const compile=(type:number,src:string)=>{const x=gl.createShader(type);if(!x)throw Error("shader");shaders.push(x);gl.shaderSource(x,src);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||"shader");return x;};program=gl.createProgram();if(!program)throw Error("program");gl.attachShader(program,compile(gl.VERTEX_SHADER,VS));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,FS));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error("link");gl.useProgram(program);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const p=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);for(const k of ["R","T","AUD","PWR","MOOD","COL","M"])u[k]=gl.getUniformLocation(program,k);}catch(e){console.warn("Voice garden fallback",e);if(program)gl.deleteProgram(program);program=null;}
 const nodes=Array.from({length:80},()=>({x:Math.random(),y:Math.random()}));let id=0,energy=0,last=performance.now();const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
 const draw=(now:number)=>{const r=n.getBoundingClientRect(),w=r.width,h=r.height;if(w<1||h<1){id=requestAnimationFrame(draw);return;}const d=Math.min(devicePixelRatio||1,1.5);if(n.width!==Math.round(w*d)||n.height!==Math.round(h*d)){n.width=Math.round(w*d);n.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);c.width=Math.round(w*.76*d);c.height=Math.round(h*d);if(gl)gl.viewport(0,0,c.width,c.height);}
 const dt=Math.min(.05,(now-last)/1000);last=now;energy+=(Math.max(0,Math.min(1,signal.current.level*1.55))-energy)*(1-Math.exp(-dt*12));const phase=live.current.state,t=Math.max(0,now-live.current.since);let spread=0,alpha=0,angle=0,size=.64;
 if(phase==="listening"){spread=1;alpha=1;size=1.12;}if(phase==="ending"){const p=Math.min(1,t/1350);spread=(1-p)**2;alpha=1-p;angle=reduced?0:p*Math.PI*3;size=.64+.48*spread;}if(phase==="speaking"||phase==="delivered"){const p=phase==="delivered"?1:1-(1-Math.min(1,t/900))**3;spread=p;alpha=p;size=.64+.48*p;}
 ctx.clearRect(0,0,w,h);const points=nodes.map((x,i)=>{const bx=(x.x-.5)*w*.92+(reduced?0:Math.sin(now/1500+i)*3),by=(x.y-.5)*h*.65;return {x:w/2+spread*(bx*Math.cos(angle)-by*Math.sin(angle)),y:h/2+spread*(bx*Math.sin(angle)+by*Math.cos(angle))};});
 if(alpha>.001){for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=points[i],b=points[j],dist=Math.hypot((nodes[i].x-nodes[j].x)*w,(nodes[i].y-nodes[j].y)*h);if(dist>90)continue;ctx.strokeStyle=`rgba(80,178,242,${alpha*(1-dist/90)*.4})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const p=reduced?.5:(now/1300+i*.31+j*.13)%1;ctx.fillStyle=`rgba(196,236,255,${alpha*.8})`;ctx.beginPath();ctx.arc(a.x+(b.x-a.x)*p,a.y+(b.y-a.y)*p,2,0,Math.PI*2);ctx.fill();}for(const p of points){ctx.fillStyle=`rgba(105,200,255,${alpha*.8})`;ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill();}}
 const glow=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,22);glow.addColorStop(0,"rgba(230,190,100,.35)");glow.addColorStop(1,"rgba(230,190,100,0)");ctx.fillStyle=glow;ctx.fillRect(w/2-22,h/2-22,44,44);
 if(gl&&program){c.style.transform=`scale(${size*(1+energy*.3)})`;gl.useProgram(program);gl.uniform2f(u.R,c.width,c.height);gl.uniform1f(u.T,reduced?0:now/1000);gl.uniform1f(u.AUD,energy);gl.uniform1f(u.PWR,.82);gl.uniform1f(u.MOOD,.7);gl.uniform3f(u.COL,.85,.69,.4);gl.uniform2f(u.M,0,0);gl.drawArrays(gl.TRIANGLES,0,3);}id=requestAnimationFrame(draw);};id=requestAnimationFrame(draw);
 return()=>{cancelAnimationFrame(id);if(gl){if(buffer)gl.deleteBuffer(buffer);if(program)gl.deleteProgram(program);for(const x of shaders)gl.deleteShader(x);}};
 },[signal]);
 return <div aria-hidden="true" style={{position:"absolute",inset:0,pointerEvents:"none"}}><style>{`.voice-router-core--landscape > canvas{visibility:hidden}`}</style><canvas ref={net} style={{position:"absolute",inset:0,width:"100%",height:"100%"}}/><canvas ref={core} style={{position:"absolute",left:"12%",top:0,width:"76%",height:"100%",filter:"brightness(1.25)"}}/></div>;
}
